// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkfW5Be75qGRwihCkByJUkProK5M6j-P4',
    appId: '1:821323672364:web:a9fd361be28eb5dfab1a89',
    messagingSenderId: '821323672364',
    projectId: 'abcdefg-c2895',
    authDomain: 'abcdefg-c2895.firebaseapp.com',
    storageBucket: 'abcdefg-c2895.appspot.com',
    measurementId: 'G-C7R03158EV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIC5XI9P06oBWi1ZWhnYo72pd-pjI3udg',
    appId: '1:821323672364:android:ad8313bec05e7bb4ab1a89',
    messagingSenderId: '821323672364',
    projectId: 'abcdefg-c2895',
    storageBucket: 'abcdefg-c2895.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC0B_54P40vo-Z2ztXFoR5ZPzPm-PUp3g',
    appId: '1:821323672364:ios:6fb7ea691a376c3bab1a89',
    messagingSenderId: '821323672364',
    projectId: 'abcdefg-c2895',
    storageBucket: 'abcdefg-c2895.appspot.com',
    androidClientId: '821323672364-2hgriavtt2286cka31r3k7t5dpqgde4v.apps.googleusercontent.com',
    iosClientId: '821323672364-2npq2msi9rru7urqhn1hjltsotdbv4l9.apps.googleusercontent.com',
    iosBundleId: 'com.example.loveTale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC0B_54P40vo-Z2ztXFoR5ZPzPm-PUp3g',
    appId: '1:821323672364:ios:6fb7ea691a376c3bab1a89',
    messagingSenderId: '821323672364',
    projectId: 'abcdefg-c2895',
    storageBucket: 'abcdefg-c2895.appspot.com',
    androidClientId: '821323672364-2hgriavtt2286cka31r3k7t5dpqgde4v.apps.googleusercontent.com',
    iosClientId: '821323672364-2npq2msi9rru7urqhn1hjltsotdbv4l9.apps.googleusercontent.com',
    iosBundleId: 'com.example.loveTale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkfW5Be75qGRwihCkByJUkProK5M6j-P4',
    appId: '1:821323672364:web:87b59fb62ff6d844ab1a89',
    messagingSenderId: '821323672364',
    projectId: 'abcdefg-c2895',
    authDomain: 'abcdefg-c2895.firebaseapp.com',
    storageBucket: 'abcdefg-c2895.appspot.com',
    measurementId: 'G-9WMTCC1LSD',
  );

}